# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-blog
  labels:
    app: personal-blog
spec:
  replicas: 2  # Number of replicas to run
  selector:
    matchLabels:
      app: personal-blog
  template:
    metadata:
      labels:
        app: personal-blog
    spec:
      containers:
      - name: personal-blog
        image: ramjeet500/personal_blog:latest  # Use your Docker Hub image
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: blog-data
          mountPath: /app/database.db  # Mount the SQLite database file
      volumes:
      - name: blog-data
        persistentVolumeClaim:
          claimName: blog-pvc  # PVC to persist SQLite database
